/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica9gasolinera;

import static java.lang.System.gc;
import java.util.Random;
import practica9gasolinera.Camion;
import practica9gasolinera.Coche;
import practica9gasolinera.Gasolinera;

/**
 *
 * @author Adria
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Pantalla p = new Pantalla();
        Random aleatorio = new Random();
        aleatorio.setSeed(System.currentTimeMillis());
        CanvasGasolinera cg = new CanvasGasolinera(1200, 800);
        Gasolinera g = new Gasolinera(cg);
        p.setSize(1200, 800);
        p.add(cg);

        p.setVisible(true);
        int sleep;
        Thread[] vehiculos = new Thread[30];
        int aleatori;
        for (int i = 1; i < 30; i++) {
            aleatori=aleatorio.nextInt(2);
            if (aleatori == 0) {

                vehiculos[i] = new Coche(g, i);
            } else if(aleatori == 1) {
                Camion camion = new Camion(g, i);
                vehiculos[i] = new Thread(camion);
            }else{
                vehiculos[i] = new Ambulancia(g, i);
                }
            
            
            vehiculos[i].start();
            try {
                //Ponemos a "Dormir" el programa durante los ms que queremos
                sleep = aleatorio.nextInt(1, 2);
                Thread.sleep(sleep * 1000);
            } catch (InterruptedException e) {

            }

        }
        for (int i = 1; i < 30; i++) {
            vehiculos[i].join();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
